In [1]:
# move to source directory
%pwd
%cd ../
%pwd
%ls

/home/yh/git/kaggle_ieee-fraud-detection
LICENSE*    data/                   log/          slackauth.json*
Makefile*   deprecated/             model/        startup-jupyter.sh*
README.md*  feature/                notebook/     test/
config/     kaggle-submit-ieee.sh*  run_gbdt.py*  util/


In [2]:
# import major modules
import pandas as pd
import numpy as np
import sys
from pathlib import Path
import seaborn as sns
import matplotlib.pyplot as plt
sys.stdout.flush()

In [8]:
# create np.ndarray
a = np.array([1, 2, 3])
print(a.dtype, a.ndim, a.shape)

int64 1 (3,)


In [10]:
b = np.array([[1], [2], [3]])
b

array([[1],
       [2],
       [3]])

In [12]:
c = np.array([[[1]], [2], [3]])
c

array([[list([1])],
       [2],
       [3]], dtype=object)

In [13]:
for i in range(3):
    print(a[i])

1
2
3


In [14]:
for i in range(4):
    print(a[i])

1
2
3


IndexError: index 3 is out of bounds for axis 0 with size 3

In [20]:
z1 = np.zeros(2, np.int32)
z1

array([0, 0], dtype=int32)

In [25]:
z2 = np.zeros(2, float)
z2.dtype

dtype('float64')

In [23]:
z3 = z1 + z2
z3

array([0., 0.])

In [26]:
np.zeros(2, float).dtype

dtype('float64')

In [35]:
X = np.array([[1, 2],
              [2, 3],
              [3, 4],
              [4, 5],
              [5, 6],
              [7, 9]])
cluster_centers = np.array([[1, 1],
                            [2, 2],
                            [3, 3]])
X.shape, cluster_centers.shape

((6, 2), (3, 2))

In [29]:
X[:, :, np.newaxis]

array([[[1],
        [2]],

       [[2],
        [3]],

       [[3],
        [4]],

       [[4],
        [5]],

       [[5],
        [6]],

       [[7],
        [9]]])

In [30]:
cluster_centers.T[np.newaxis, :, :]

array([[[1, 2, 3],
        [1, 2, 3]]])

In [44]:
X[3, :]

array([4, 5])

In [46]:
X = np.array([[[1,  2,  3],
                   [4,  5,  6]],

                  [[7,  8,  9],
                   [10, 11, 12]]])
X.shape

(2, 2, 3)

In [58]:
# pandas
df_simple = pd.DataFrame(np.arange(12).reshape(3, 4))
df_simple

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [63]:
df_simple.values, df_simple.columns, df_simple.index

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 RangeIndex(start=0, stop=4, step=1),
 RangeIndex(start=0, stop=3, step=1))

In [66]:
df = pd.DataFrame(np.arange(12).reshape(3, 4), 
                 columns=['col_0', 'col_1', 'col_2', 'col_3'], 
                 index=['row_0', 'row_1', 'row_2'])
df

(       col_0  col_1  col_2  col_3
 row_0      0      1      2      3
 row_1      4      5      6      7
 row_2      8      9     10     11,
 Index(['col_0', 'col_1', 'col_2', 'col_3'], dtype='object'),
 Index(['row_0', 'row_1', 'row_2'], dtype='object'))

In [67]:
df.columns, df.index

(Index(['col_0', 'col_1', 'col_2', 'col_3'], dtype='object'),
 Index(['row_0', 'row_1', 'row_2'], dtype='object'))

In [68]:
df.columns

Index(['col_0', 'col_1', 'col_2', 'col_3'], dtype='object')

In [70]:
df.columns[0] = 'col_0_mod'

TypeError: Index does not support mutable operations

In [77]:
df.columns=['Col_0', 'Col_1', 'Col_2', 'Col_3']
df.index = ['Row_0', 'Row_1', 'Row_2']
df

Col_0  Col_1  Col_2  Col_3
Row_0      0      1      2      3
Row_1      4      5      6      7
Row_2      8      9     10     11

In [80]:
df['Col_1']['Row_1']

5

In [88]:
arr = np.array(np.arange(12).reshape(3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
columns = ['c1', 'c2', 'c3', 'c4']
index = ['i1', 'i2', 'i3']
df = pd.DataFrame(arr, columns=columns, index=index)
df

c1  c2  c3  c4
i1   0   1   2   3
i2   4   5   6   7
i3   8   9  10  11

In [97]:
df.set_index('c1')

c2  c3  c4
c1            
0    1   2   3
4    5   6   7
8    9  10  11

In [98]:
df.reset_index().index=index
df

c1  c2  c3  c4
i1   0   1   2   3
i2   4   5   6   7
i3   8   9  10  11

In [99]:
df.set_index(['c1', 'c2'])

c3  c4
c1 c2        
0  1    2   3
4  5    6   7
8  9   10  11

In [102]:
df.set_index('c3', append=True)

c1  c2  c4
   c3            
i1 2    0   1   3
i2 6    4   5   7
i3 10   8   9  11

In [103]:
df.reset_index()

index  c1  c2  c3  c4
0    i1   0   1   2   3
1    i2   4   5   6   7
2    i3   8   9  10  11

In [105]:
df.index = index
df

c1  c2  c3  c4
i1   0   1   2   3
i2   4   5   6   7
i3   8   9  10  11

In [218]:
df = pd.DataFrame([
    ['A','B','C'],
    ['A','D','E'],
    ['A','D','F']]
)
df

0  1  2
0  A  B  C
1  A  D  E
2  A  D  F

In [219]:
df.columns = ['c1', 'c2', 'c3']
df.index = ['i1', 'i2', 'i3']
df

c1 c2 c3
i1  A  B  C
i2  A  D  E
i3  A  D  F

In [220]:
df.set_index(['c1', 'c2'])

c3
c1 c2   
A  B   C
   D   E
   D   F

In [221]:
df

c1 c2 c3
i1  A  B  C
i2  A  D  E
i3  A  D  F

In [225]:
df.set_index(['c1', 'c2'], inplace=True, append=True)
df, df.index.names

(         c3
    c1 c2   
 i1 A  B   C
 i2 A  D   E
 i3 A  D   F, FrozenList([None, 'c1', 'c2']))

In [226]:
df.reset_index(level=['c1', 'c2'], inplace=True)
df

c1 c2 c3
i1  A  B  C
i2  A  D  E
i3  A  D  F